#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('tastphp-installer','v1.0.0');

$application->add(new \Tastphp\Installer\Console\InstallerCommand());

$application->run();
