#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$application = new Application('tastphp-installer','v1.0.0');

$application->add(new \Tastphp\Installer\Console\InstallerCommand());

$application->run();